project:
  type: website

website:
  title: "Google Summer of Code 2025 | NUMFOCUS | QuTiP-QOC"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Akhils777/
format:
  html:
    theme: cosmo
    css: styles.css